// -------------------------------------------------------------
// 
// File Name: C:\Users\aksha\OneDrive\Documents\Projects\hdl-tutorial\ch07\codegen\pid_controller_fixpt\hdlsrc\pid_controller_fixpt.v
// Created: 2026-07-27 13:46:46
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// u                             ce_out        1
// saturated                     ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pid_controller_fixpt
// Source Path: pid_controller_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pid_controller_fixpt
          (clk,
           reset,
           clk_enable,
           error,
           valid,
           Kp,
           Ki_Ts,
           Kd_Ts,
           uMax,
           uMin,
           ce_out,
           u,
           saturated);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] error;  // sfix16_En14
  input   valid;
  input   signed [15:0] Kp;  // sfix16_En12
  input   signed [15:0] Ki_Ts;  // sfix16_En14
  input   signed [15:0] Kd_Ts;  // sfix16_En12
  input   signed [15:0] uMax;  // sfix16_En14
  input   signed [15:0] uMin;  // sfix16_En14
  output  ce_out;
  output  signed [15:0] u;  // sfix16_En14
  output  saturated;


  wire enb;
  wire signed [15:0] u_1;  // sfix16_En14
  wire signed [31:0] ki_prod;  // sfix32_En28
  reg signed [15:0] error_prev;  // sfix16_En14
  wire signed [15:0] tmp;  // sfix16_En14
  wire signed [31:0] integrator;  // sfix32_En28
  wire signed [31:0] tmp_1;  // sfix32_En28
  wire signed [32:0] p23tmp_sub_cast;  // sfix33_En28
  wire signed [32:0] p23tmp_sub_cast_1;  // sfix33_En28
  wire signed [32:0] p23tmp_sub_temp;  // sfix33_En28
  wire signed [31:0] tmp_2;  // sfix32_En28
  wire signed [32:0] p22tmp_sub_cast;  // sfix33_En28
  wire signed [32:0] p22tmp_sub_cast_1;  // sfix33_En28
  wire signed [32:0] p22tmp_sub_temp;  // sfix33_En28
  wire signed [31:0] raw;  // sfix32_En28
  wire raw_1;
  wire signed [31:0] p19raw_cast;  // sfix32_En28
  wire signed [31:0] tmp_3;  // sfix32_En28
  wire raw_2;
  wire signed [31:0] tmp_4;  // sfix32_En28
  reg signed [31:0] integrator_1;  // sfix32_En28
  wire signed [31:0] tmp_5;  // sfix32_En28
  wire signed [32:0] p24integrator_add_cast;  // sfix33_En28
  wire signed [32:0] p24integrator_add_cast_1;  // sfix33_En28
  wire signed [32:0] p24integrator_add_temp;  // sfix33_En28
  wire signed [31:0] p21raw_mul_temp;  // sfix32_En26
  wire signed [34:0] p21raw_add_cast;  // sfix35_En28
  wire signed [34:0] p21raw_add_cast_1;  // sfix35_En28
  wire signed [34:0] p21raw_add_temp;  // sfix35_En28
  wire signed [35:0] p21raw_add_cast_2;  // sfix36_En28
  wire signed [16:0] p21raw_sub_cast;  // sfix17_En14
  wire signed [16:0] p21raw_sub_cast_1;  // sfix17_En14
  wire signed [16:0] p21raw_sub_temp;  // sfix17_En14
  wire signed [32:0] p21raw_mul_temp_1;  // sfix33_En26
  wire signed [35:0] p21raw_add_cast_3;  // sfix36_En28
  wire signed [35:0] p21raw_add_temp_1;  // sfix36_En28
  wire signed [31:0] p13raw_cast;  // sfix32_En28
  wire signed [15:0] tmp_6;  // sfix16_En14
  wire signed [15:0] tmp_7;  // sfix16_En14
  wire signed [15:0] tmp_8;  // sfix16_En14
  wire signed [15:0] tmp_9;  // sfix16_En14
  wire saturated_1;
  wire saturated_2;
  wire saturated_3;
  wire tmp_10;
  wire saturated_4;
  wire tmp_11;
  wire tmp_12;


  // Proportional
  assign u_1 = 16'sb0000000000000000;

  // Derivative
  assign ki_prod = Ki_Ts * error;

  assign enb = clk_enable;

  assign tmp = (valid == 1'b0 ? error_prev :
              error);

  always @(posedge clk or posedge reset)
    begin : error_prev_reg_process
      if (reset == 1'b1) begin
        error_prev <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          error_prev <= tmp;
        end
      end
    end

  assign p23tmp_sub_cast = {integrator[31], integrator};
  assign p23tmp_sub_cast_1 = {ki_prod[31], ki_prod};
  assign p23tmp_sub_temp = p23tmp_sub_cast - p23tmp_sub_cast_1;
  assign tmp_1 = ((p23tmp_sub_temp[32] == 1'b0) && (p23tmp_sub_temp[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((p23tmp_sub_temp[32] == 1'b1) && (p23tmp_sub_temp[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(p23tmp_sub_temp[31:0])));

  assign p22tmp_sub_cast = {integrator[31], integrator};
  assign p22tmp_sub_cast_1 = {ki_prod[31], ki_prod};
  assign p22tmp_sub_temp = p22tmp_sub_cast - p22tmp_sub_cast_1;
  assign tmp_2 = ((p22tmp_sub_temp[32] == 1'b0) && (p22tmp_sub_temp[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((p22tmp_sub_temp[32] == 1'b1) && (p22tmp_sub_temp[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(p22tmp_sub_temp[31:0])));

  assign p19raw_cast = {{2{uMin[15]}}, {uMin, 14'b00000000000000}};
  assign raw_1 = raw < p19raw_cast;

  assign tmp_3 = (raw_1 == 1'b0 ? integrator :
              tmp_2);

  assign tmp_4 = (raw_2 == 1'b0 ? tmp_3 :
              tmp_1);

  assign tmp_5 = (valid == 1'b0 ? integrator_1 :
              tmp_4);

  always @(posedge clk or posedge reset)
    begin : integrator_reg_process
      if (reset == 1'b1) begin
        integrator_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          integrator_1 <= tmp_5;
        end
      end
    end

  assign p24integrator_add_cast = {integrator_1[31], integrator_1};
  assign p24integrator_add_cast_1 = {ki_prod[31], ki_prod};
  assign p24integrator_add_temp = p24integrator_add_cast + p24integrator_add_cast_1;
  assign integrator = ((p24integrator_add_temp[32] == 1'b0) && (p24integrator_add_temp[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((p24integrator_add_temp[32] == 1'b1) && (p24integrator_add_temp[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(p24integrator_add_temp[31:0])));

  // Saturate with anti-windup
  // Sum all components (cast to 32-bit)
  // Integral (cast result back to 32-bit)
  assign p21raw_mul_temp = Kp * error;
  assign p21raw_add_cast = {p21raw_mul_temp[31], {p21raw_mul_temp, 2'b00}};
  assign p21raw_add_cast_1 = {{3{integrator[31]}}, integrator};
  assign p21raw_add_temp = p21raw_add_cast + p21raw_add_cast_1;
  assign p21raw_add_cast_2 = {p21raw_add_temp[34], p21raw_add_temp};
  assign p21raw_sub_cast = {error[15], error};
  assign p21raw_sub_cast_1 = {error_prev[15], error_prev};
  assign p21raw_sub_temp = p21raw_sub_cast - p21raw_sub_cast_1;
  assign p21raw_mul_temp_1 = Kd_Ts * p21raw_sub_temp;
  assign p21raw_add_cast_3 = {p21raw_mul_temp_1[32], {p21raw_mul_temp_1, 2'b00}};
  assign p21raw_add_temp_1 = p21raw_add_cast_2 + p21raw_add_cast_3;
  assign raw = ((p21raw_add_temp_1[35] == 1'b0) && (p21raw_add_temp_1[34:31] != 4'b0000) ? 32'sb01111111111111111111111111111111 :
              ((p21raw_add_temp_1[35] == 1'b1) && (p21raw_add_temp_1[34:31] != 4'b1111) ? 32'sb10000000000000000000000000000000 :
              $signed(p21raw_add_temp_1[31:0])));

  assign p13raw_cast = {{2{uMax[15]}}, {uMax, 14'b00000000000000}};
  assign raw_2 = raw > p13raw_cast;

  assign tmp_6 = (((raw[31] == 1'b0) && (raw[30:29] != 2'b00)) || ((raw[31] == 1'b0) && (raw[29:14] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((raw[31] == 1'b1) && (raw[30:29] != 2'b11) ? 16'sb1000000000000000 :
              raw[29:14] + $signed({1'b0, raw[13]})));

  assign tmp_7 = (raw_1 == 1'b0 ? tmp_6 :
              uMin);

  assign tmp_8 = (raw_2 == 1'b0 ? tmp_7 :
              uMax);

  assign tmp_9 = (valid == 1'b0 ? u_1 :
              tmp_8);

  assign u = tmp_9;

  assign saturated_1 = 1'b0;

  assign saturated_2 = 1'b0;

  assign saturated_3 = 1'b1;

  assign tmp_10 = (raw_1 == 1'b0 ? saturated_2 :
              saturated_3);

  assign saturated_4 = 1'b1;

  assign tmp_11 = (raw_2 == 1'b0 ? tmp_10 :
              saturated_4);

  assign tmp_12 = (valid == 1'b0 ? saturated_1 :
              tmp_11);

  assign saturated = tmp_12;

  assign ce_out = clk_enable;

endmodule  // pid_controller_fixpt

